name: Sonar

on:
  push:

jobs:
  build:
    if: github.repository == 'pepepopo-bot/test_repo'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
    name: "Java ${{ matrix.java }} build"
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "${{ matrix.java }}"
          cache: "maven"
      - name: Verify build
        run: mvn verify -P metrics
      - name: Report metrics
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=pepepopo-bot_test_repo
