name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Java ${{ matrix.java }} build"
    steps:
      - name: 'Test for Sonar secret'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
            echo "SONAR_TOKEN_SET=$(test ${SONAR_TOKEN} && echo true)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Check
        run: mvn -B -Pmetrics verify
      - name: Sonar
        if: env.SONAR_TOKEN_SET == 'true'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=pepepopo-bot_test_repo
      - name: Save PR number
        if: github.event_name == 'pull_request'
        run: |
          echo ${{ github.event.number }} > PR_NUMBER.txt
          echo ${{ env.SONAR_TOKEN_SET }}
      - name: Archive PR number
        if: env.SONAR_TOKEN_SET != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: PR_NUMBER
          path: PR_NUMBER.txt


