name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]
        include:
          - java: 17
            metrics: true
    name: "Java ${{ matrix.java }} build"
    steps:
      - name: Init variables
        run: |
          [[ "${{ github.repository }}" == "pepepopo-bot/test_repo" ]] && echo "SONAR_ENABLED=true" >> "$GITHUB_ENV"
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "${{ matrix.java }}"
          cache: "maven"
      - name: Verify build
        run: |
          MAVEN_ARGS="verify"
          if [[ "${{ env.SONAR_ANALYSIS }}" ]]; then
            MAVEN_ARGS="$MAVEN_ARGS -P metrics"
          fi
          mvn $MAVEN_ARGS
      - name: Report metrics
        if: matrix.metrics && env.SONAR_ENABLED
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=pepepopo-bot_test_repo
