name: Score
on:
  push:
    branches: ["main"]
  branch_protection_rule:
  schedule:
    - cron: '27 9 * * 6'

permissions: 
  contents: read
  security-events: write
  id-token: write

jobs:
  scoreca:
    uses: pepepopo-bot/workflows/.github/workflows/scorecards.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      

