name: Sonar Build

on:
  push:
  pull_request:

jobs:
  report:
    if: github.repository == 'pepepopo-bot/test_repo'
    runs-on: ubuntu-latest
    name: "Generate report"
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - name: Build project
        run: mvn verify -P metrics
      - name: Upload artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: "**/target"
      - name: Prepare arguments
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          echo ${{ github.event.pull_request.number }} >> pr-event.txt
          echo ${{ github.event.pull_request.head.ref }} >> pr-event.txt
          echo ${{ github.event.pull_request.base.ref }} >> pr-event.txt
          echo ${{ github.event.pull_request.head.sha }} >> pr-event.txt
      - name: Upload parameters
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: pr-event
          path: pr-event.txt
      - name: Report metrics
        if: github.event_name == 'push'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=pepepopo-bot_test_repo
