name: Test

on:
  pull_request_target:
    types: [labeled, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    name: Prepare parameters
    steps:
      - name: Prepare parameters
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request
            console.log(labels)
