name: test.yml
# nuné v cílovém repu povolit vytváření PR v gh actions!!!
on:
  pull_request_target:
    types: [labeled]

jobs:
  backport:
    if: github.event.label.name == 'backport'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      BACKPORT_TARGET_BRANCH: prod
      BACKPORT_BRANCH: backport/pr-${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BACKPORT_TARGET_BRANCH }}
          fetch-depth: 0

      - run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch

      - id: commits
        run: |
          git log --format="%H" ${{ env.BACKPORT_TARGET_BRANCH }}..pr-branch > commits.txt

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - run: |
          git checkout -b ${{ env.BACKPORT_BRANCH }}
          while read -r sha; do
            git cherry-pick "$sha" || {
            echo "Conflict in $sha"
            git cherry-pick --abort
            exit 1
          }
          done < commits.txt

      - run: git push origin ${{ env.BACKPORT_BRANCH }}

      - run: |
          curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "$(jq -n \
              --arg title "Backport #${{ github.event.pull_request.number }}" \
              --arg body "Automatický backport PR #${{ github.event.pull_request.number }}" \
              --arg head "${{ env.BACKPORT_BRANCH }}" \
              --arg base "${{ env.BACKPORT_TARGET_BRANCH }}" \
              '{title: $title, body: $body, head: $head, base: $base}')"
# možnost konfliktu

